name: Go Test and Lint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run tests with race detector and coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Run stress tests with race detector
      # -tags=stress 플래그를 추가하여 스트레스 테스트를 실행합니다.
      # 이 테스트들은 시간이 더 오래 걸릴 수 있습니다.
      run: go test -race -tags=stress ./...

    - name: Run race tests with race detector
      # -tags=race 플래그를 추가하여 레이스 테스트를 실행합니다.
      run: go test -race -tags=race ./...

    - name: Run benchmarks
      run: |
        echo "Running benchmarks with shorter duration for CI..."
        go test -bench=. -benchmem -benchtime=500ms -timeout=3m ./... || echo "Benchmarks completed with some failures"
      continue-on-error: true
      
    - name: Check for test failures
      if: failure()
      run: |
        echo "Tests failed. Please check the logs above."
        exit 1
